#!/bin/sh -e

get_adapter() {
	name=$1
	echo Cloning $name adapter
	git clone https://github.com/tagdara/sofa-adapter-$1 /opt/sofa-server/adapters/$1
	pip3 install -r /opt/sofa-server/adapters/$1/requirements.txt || true
	python3 /opt/sofa-server/svcmgr.py  $1
}

get_adapter $1
