#!/bin/sh -e

make_repo() {
	name=$1
	cd /opt/sofa-server/adapters/$name
	touch /opt/sofa-server/adapters/$name/README.md
	curl -u tagdara https://api.github.com/user/repos -d '{"name":"sofa-adapter-'$name'"}'
	git init
	git add --all
	git commit -m "first sofa adapter $name commit"
	git remote add origin https://github.com/tagdara/sofa-adapter-$name.git
	git push -u origin master
}
make_repo $1
