#!/usr/bin/env bash

push_adapter() {
	adapter=$f
        echo Updating Git for $adapter
        cd $adapter
	ls
	git config credential.helper store       
 	git add --all
        git commit -m "fixes and enhancements"
        git push
}

name=$0
pass=$1

for f in /opt/sofa-server/adapters/*; do
    if [ -d ${f} ]; then
        # Will not run if no directories are available
        echo $f
	push_adapter
    fi
done
